# vim:et:ts=2:sw=2
language: python
python:
  - 3.6
addons:
  apt:
    packages:
      - libxkbcommon-x11-0
before_install:
  - pip install PyQt5 black isort
install:
  - pip freeze
before_script:
  - isort --check elogviewer.py tests.py setup.py
  - black --check elogviewer.py tests.py setup.py
script:
  - xvfb-run -a python tests.py
