# vim:et:ts=2:sw=2
language: python
python:
  - 3.6
addons:
  apt:
    packages:
      - libxkbcommon-x11-0
install:
  - pip install PyQt5==5.13.2
  - pip install pyfakefs pytest pytest-black pytest-isort pytest-qt
  - pip freeze
script:
  - xvfb-run -a python -m pytest --black --isort tests
