---

- hosts: all
  tasks:

  - name: Configure locale
    ansible.builtin.lineinfile:
      path: /etc/locale.gen
      regexp: '^#?en_US\.UTF-8'
      line: 'en_US.UTF-8 UTF-8'
    become: yes

  - name: Generate locale
    ansible.builtin.command: locale-gen
    become: yes

  - name: Configure `make.conf`
    ansible.builtin.template:
        src: make_conf.j2
        dest: /etc/portage/make.conf
        mode: 0644
        backup: yes
    become: yes
    vars:
        ncpus: 4
        use_python: 3.12
        python_targets: python3_12
        qt_use_flag: qt6

  - name: Configure per-package USE flags
    ansible.builtin.lineinfile:
        create: yes
        path: /etc/portage/package.use/opts
        line: '{{ item }}'
        state: present
    become: yes
    loop:
        # Check packages / use flag with `euse -I $USE`
        - app-crypt/gpgme -qt5
        - app-crypt/pinentry -qt5
        - app-editors/vim -X
        - dev-build/cmake -qt5
        - dev-libs/libpcre2 pcre16
        - dev-python/PyQt5 gui
        - dev-python/PyQt5 testlib
        - dev-python/PyQt5 widgets
        - sys-apps/groff -X
        - sys-kernel/installkernel dracut
        - x11-base/xorg-server suid
        - x11-libs/libxcb xkb
        - x11-wm/openbox session

  - name: Create cache dir
    ansible.builtin.file:
        path: "/var/cache/{{ item }}"
        state: directory
        group: portage
        mode: 0755
    become: yes
    loop: ['binpkgs', 'distfiles']

  - name: Configure cache
    ansible.builtin.lineinfile:
        path: /etc/portage/make.conf
        regexp: '^{{ item.env }}='
        line: '{{ item.env }}="/var/cache/{{ item.dest }}"'
    become: yes
    loop:
        - { env: 'DISTDIR', dest: 'distfiles' }
        - { env: 'PKGDIR', dest: 'binpkgs' }

  - name: Sync tree
    ansible.builtin.command: /usr/bin/emerge --sync
    become: yes
    tags: sync, never

  - block:
    - name: Upload cache
      ansible.builtin.synchronize:
          mode: push
          src: '.cache/{{ item }}/'
          dest: '/var/cache/{{ item }}/'
          use_ssh_args: yes
      loop: ['binpkgs', 'distfiles']
      ignore_errors: yes

    - name: Update system
      ansible.builtin.command: /usr/bin/emerge --update --deep --changed-use @system

    - name: Update cache [system]
      ansible.builtin.synchronize:
          mode: pull
          src: '/var/cache/{{ item }}/'
          dest: '.cache/{{ item }}/'
      become: no
      loop: ['binpkgs', 'distfiles']

    - name: Install `equery` (for portage module)
      ansible.builtin.command: /usr/bin/emerge app-portage/gentoolkit

    - name: Clean up packages
      community.general.portage:
          package: net-wireless/wireless-tools
          state: absent
          depclean: yes

    - name: Update world
      community.general.portage:
          package: '@world'
          update: yes
          deep: yes
          changed_use: yes
      register: update_world
      ignore_errors: yes

    - name: Update cache [world]
      ansible.builtin.synchronize:
          mode: pull
          src: '/var/cache/{{ item }}/'
          dest: '.cache/{{ item }}/'
      become: no
      loop: ['binpkgs', 'distfiles']
      when: update_world is succeeded

    - name: Reboot after updates
      ansible.builtin.reboot:
      tags: reboot, never

    - name: Install packages
      community.general.portage:
          name:
              - acct-group/adm
              - acct-group/audio
              - acct-group/dialout
              - acct-group/portage
              - acct-group/users
              - acct-group/vboxsf
              - acct-group/vboxguest
              - acct-group/vboxusers
              - acct-group/video
              - acct-group/wheel
              - acct-user/vboxguest
              - app-admin/sudo
              - app-emulation/virtualbox-guest-additions
              - app-emulation/virtualbox-guest-modules
              - dev-python/pip
              - dev-python/pytest
              - dev-python/pyqt6
              - x11-base/xorg-server
              - x11-misc/menumaker
              - x11-terms/xterm
              - x11-wm/openbox
              - x11-wm/twm
          state: present

    - name: Trim cache
      ansible.builtin.command: '/usr/bin/eclean {{ item }}'
      loop: ['distfiles', 'packages']

    - name: Download cache
      ansible.builtin.synchronize:
          mode: pull
          src: '/var/cache/{{ item }}/'
          dest: '.cache/{{ item }}/'
          delete: yes
      become: no
      loop: ['binpkgs', 'distfiles']
      ignore_errors: yes

    become: yes

  - name: Set machine-id for dbus
    ansible.builtin.shell: /usr/bin/dbus-uuidgen > /var/lib/dbus/machine-id
    become: yes

  - block:
    - name: Add user
      ansible.builtin.user:
          name: gentoo
          state: present
          password: '{{ "gentoo" | password_hash("sha256") }}'
          groups: [adm, audio, dialout, portage, users, vboxsf, vboxusers, video, wheel]
      become: yes

    - name: Make user omnipotent
      ansible.builtin.lineinfile:
          path: /etc/sudoers.d/gentoo
          line: "gentoo\tALL=(ALL)\tNOPASSWD: ALL"
          validate: 'visudo -cf %s'
          state: present
          create: yes
          owner: root
          group: root
          mode: 0440
      become: yes

  - block:
    - name: Create OpenBox menu
      ansible.builtin.command: /usr/bin/mmaker -f OpenBox3
      become_user: gentoo

    - name: Set xsession env
      ansible.builtin.lineinfile:
          path: /home/gentoo/.bashrc
          line: 'export XSESSION=openbox'
          state: present
          create: yes
          owner: gentoo
          group: gentoo

    become: yes

  - name: Copy dist
    ansible.builtin.synchronize:
        mode: push
        src: '../dist'
        dest: '/home/gentoo/'
        group: no
        owner: no
    become: yes
    become_user: gentoo
