default:
    just --list

test:
    cd roles/gentoo_base && uv run --extra vm molecule test

e2e:
    uv run --extra vm molecule test --scenario-name e2e

start:
    vagrant --provision up

stop:
    vagrant halt

provision: start
    vagrant provision

reboot: start
    ansible -i inventory gentoo -m ansible.builtin.reboot -b

destroy:
    vagrant -f destroy

ssh: start
	vagrant ssh
