---
- name: Create cache dirs # noqa: risky-file-permissions
  ansible.builtin.file:
    path: "/var/cache/{{ item }}"
    state: directory
  loop: ["binpkgs", "distfiles"]
  changed_when: false

- name: Trim cache
  ansible.builtin.command: "/usr/bin/eclean {{ item }}"
  loop: ["distfiles", "packages"]
  changed_when: false

- name: Download cache
  ansible.posix.synchronize:
    mode: pull
    src: "{{ item.src }}/"
    dest: "{{ item.dest }}/"
    delete: true
  become: false
  loop:
    - { src: /var/cache/binpkgs, dest: "{{ gentoo_system_cache_binpkgs }}" }
    - { src: /var/cache/distfiles, dest: "{{ gentoo_system_cache_distfiles }}" }
  failed_when: false
  changed_when: false
