---
- name: Check last sync time
  ansible.builtin.stat:
    path: /var/db/repos/gentoo/metadata/timestamp.chk
  register: gentoo_system_sync_timestamp
  tags: sync

- name: "Sync tree"
  ansible.builtin.command: /usr/bin/emerge --sync
  tags: sync
  when:
    - gentoo_run_sync | default(false)
    - not gentoo_system_sync_timestamp.stat.exists or
      (ansible_date_time.epoch | int) - (gentoo_system_sync_timestamp.stat.mtime | int) > 86400
  changed_when: false
  retries: 3 # rsync may be flaky in the CI.
  delay: 30

- name: "Upload cache"
  ansible.builtin.import_tasks: "upload_cache.yml"

- name: Install `equery` (for portage module)
  community.general.portage:
    package: app-portage/gentoolkit
    state: present

- name: "Update system"
  ansible.builtin.import_tasks: "update_system.yml"

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

- name: "Update world"
  ansible.builtin.import_tasks: "update_world.yml"

- name: "Install required packages"
  ansible.builtin.import_tasks: "install.yml"

- name: "Download cache"
  ansible.builtin.import_tasks: "download_cache.yml"
