---
- name: Update @system
  block:
    - name: Update system
      ansible.builtin.command: |
        /usr/bin/emerge --update --deep --changed-use @system
      register: gentoo_system_update_system
      changed_when: gentoo_system_update_system.stdout is search('sys-kernel/')

    - name: Report cache hits [system]
      ansible.builtin.include_tasks: report_cache_hits.yml
      vars:
        _output: "{{ gentoo_system_update_system.stdout }}"

    - name: Update cache [system]
      ansible.posix.synchronize:
        mode: pull
        src: "/var/cache/{{ item }}/"
        dest: ".cache/{{ item }}/"
      become: false
      loop: ["binpkgs", "distfiles"]

- name: "Request reboot after updates"  # noqa: no-handler
  ansible.builtin.meta: noop
  when: gentoo_system_update_system.changed
  notify: Reboot system
