---
- name: Update @system
  block:
    - name: Update system
      community.general.portage:
        package: "@system"
        update: true
        deep: true
        changed_use: true
      register: gentoo_system_update_system

    - name: Report cache hits [system]
      ansible.builtin.include_tasks: report_cache_hits.yml
      vars:
        _output: "{{ gentoo_system_update_system.msg }}"

    - name: Update cache [system]
      ansible.posix.synchronize:
        mode: pull
        src: "/var/cache/{{ item }}/"
        dest: ".cache/{{ item }}/"
      become: false
      loop: ["binpkgs", "distfiles"]

- name: "Request reboot after updates"  # noqa: no-handler
  ansible.builtin.meta: noop
  when: gentoo_system_update_system.msg is search('sys-kernel/')
  notify: Reboot system
