---
- name: Create local cache directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ gentoo_system_cache_binpkgs }}"
    - "{{ gentoo_system_cache_distfiles }}"
  delegate_to: localhost
  become: false
  changed_when: false

- name: Upload cache
  ansible.posix.synchronize:
    mode: push
    src: "{{ item.src }}/"
    dest: "{{ item.dest }}/"
    use_ssh_args: true
  loop:
    - {src: "{{ gentoo_system_cache_binpkgs }}", dest: /var/cache/binpkgs}
    - {src: "{{ gentoo_system_cache_distfiles }}", dest: /var/cache/distfiles}
  failed_when: false
  changed_when: false
