---
- name: Install packages
  community.general.portage:
    name:
      - acct-group/adm
      - acct-group/audio
      - acct-group/dialout
      - acct-group/portage
      - acct-group/users
      - acct-group/video
      - acct-group/wheel
      - app-admin/sudo
    state: present
  register: gentoo_system_install

- name: Report cache hits [install]
  ansible.builtin.include_tasks: report_cache_hits.yml
  vars:
    _output: "{{ gentoo_system_install.msg }}"
