---
- name: Report cache hits
  ansible.builtin.debug:
    msg: >-
      Cache hits: {{ _output | regex_findall('\[binary') | length }},
      built from source: {{ _output | regex_findall('\[ebuild') | length }},
      news items pending:
      {{ (_output | regex_search('([0-9]+) news items? needs? reading', '\1') | default([0], true)) | first }}
