---
- name: Update @system
  block:
    - name: Update system
      community.general.portage:
        package: "@system"
        update: true
        deep: true
        changed_use: true
      register: gentoo_system_update_system
      changed_when: false

    - name: Detect system Python version
      ansible.builtin.command:
        cmd: python3 -c "import sys; print('python{}_{}'.format(*sys.version_info[:2]))"
      register: _gentoo_system_python_detected
      changed_when: false
      when: gentoo_manage_python_targets | default(true)

    - name: Configure make.conf/10_python_targets
      ansible.builtin.template:
        src: make_conf_python_targets.j2
        dest: /etc/portage/make.conf/10_python_targets
        mode: "0644"
      vars:
        _python_targets: "{{ python_targets | default(_gentoo_system_python_detected.stdout | default('')) }}"
        _python_single_target: "{{ python_single_target | default(python_targets | default(_gentoo_system_python_detected.stdout | default(''))) }}"
      changed_when: false
      when: gentoo_manage_python_targets | default(true)

    - name: Remove make.conf/10_python_targets
      ansible.builtin.file:
        path: /etc/portage/make.conf/10_python_targets
        state: absent
      when: not gentoo_manage_python_targets | default(true)

    - name: Rebuild system with Python targets
      community.general.portage:
        package: "@system"
        update: true
        deep: true
        changed_use: true
      register: gentoo_system_rebuild_system
      changed_when: false

    - name: Report cache hits [system]
      ansible.builtin.include_tasks: report_cache_hits.yml
      vars:
        _output: "{{ gentoo_system_update_system.msg }}"

    - name: Report cache hits [system rebuild]
      ansible.builtin.include_tasks: report_cache_hits.yml
      vars:
        _output: "{{ gentoo_system_rebuild_system.msg }}"

    - name: Update cache [system]
      ansible.posix.synchronize:
        mode: pull
        src: "{{ item.src }}/"
        dest: "{{ item.dest }}/"
      become: false
      loop:
        - src: /var/cache/binpkgs
          dest: "{{ gentoo_cache_binpkgs }}"
        - src: /var/cache/distfiles
          dest: "{{ gentoo_cache_distfiles }}"
      failed_when: false
      changed_when: false

- name: "Request reboot after updates" # noqa: no-handler
  ansible.builtin.debug:
    msg: "Kernel update detected, requesting reboot"
  when:
    - gentoo_allow_reboot | default(true)
    - gentoo_system_update_system.msg is search('sys-kernel/')
  notify: Reboot system
