---
gentoo_base_manage_gentoo_manage_python_targets: true

gentoo_base_package_use_lines:
  # Check packages / use flag with `euse -I $USE`
  - app-crypt/pinentry -qt6
  - app-editors/vim -X
  - dev-libs/libpcre2 pcre16
  - dev-python/pyqt6 testlib
  - dev-python/qtpy testlib
  - sys-apps/groff -X
  - sys-kernel/installkernel dracut
  - x11-base/xorg-server suid
  - x11-libs/libxcb xkb
  - x11-wm/openbox session
