---
- name: Render templates
  hosts: all
  gather_facts: false
  tasks:
    - name: Render make.conf templates
      ansible.builtin.import_tasks: converge_make_conf.yml
    - name: Render package.use templates
      ansible.builtin.import_tasks: converge_package_use.yml
