---
- name: Render 00_base
  ansible.builtin.template:
    src: "{{ playbook_dir | dirname | dirname }}/templates/make_conf_base.j2"
    dest: "/tmp/molecule_make_conf_{{ item }}_base"
    mode: "0644"
  vars:
    ncpus: 4
    gentoo_base_qt_use_flag: "{{ item }}"
  loop:
    - qt6
    - qt5
