---
- name: Verify templates
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify make.conf templates
      ansible.builtin.import_tasks: verify_make_conf.yml
    - name: Verify package.use templates
      ansible.builtin.import_tasks: verify_package_use.yml
