---
ansible_python_interpreter: /usr/bin/python3.13

python_targets: "python3_13 python3_14"
python_single_target: "python3_13"

gentoo_cache_binpkgs: .cache/vagrant/binpkgs
gentoo_cache_distfiles: .cache/distfiles

gentoo_base_qt_use_flag: "qt6"

gentoo_user_name: "gentoo"
gentoo_user_password: "gentoo"
gentoo_user_groups:
  - adm
  - audio
  - dialout
  - portage
  - users
  - video
  - wheel
