---
name: ansible-test

on:
  push:
    branches: [main]
    paths:
      - 'vm/**'
      - 'uv.lock'
  pull_request:
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.13'

jobs:
  ansible-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-ansible
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Test ansible roles
        run: cd vm/roles/gentoo_base && uv run --extra vm molecule test
      - name: Publish test results
        uses: mikepenz/action-junit-report@v6
        if: ${{ !cancelled() }}
        with:
          report_paths: vm/roles/gentoo_base/junit/*.xml

  all-checks:
    if: ${{ !cancelled() }}
    needs: [ansible-test]
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - if: >-
          ${{ contains(needs.*.result, 'failure')
          || contains(needs.*.result, 'cancelled') }}
        run: exit 1
