---
name: e2e

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - 'roles/**'
      - 'molecule/**'
      - 'uv.lock'
  schedule:
    # First day of every month at 2:00 AM UTC.
    - cron: '0 2 1 * *'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.13'

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-ansible
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Restore cache
        uses: actions/cache@v6.1.0
        with:
          path: |
            .cache/docker/binpkgs
            .cache/distfiles
            .cache/repos
          key: gentoo-e2e-${{ github.run_id }}
          restore-keys: gentoo-e2e-
      - name: Run e2e scenario
        run: uv run --group vm molecule test --scenario-name e2e
      - name: Save cache
        uses: actions/cache/save@v6.1.0
        if: ${{ !cancelled() }}
        with:
          path: |
            .cache/docker/binpkgs
            .cache/distfiles
            .cache/repos
          key: gentoo-e2e-${{ github.run_id }}
      - name: Publish e2e test results
        uses: mikepenz/action-junit-report@v6
        if: ${{ !cancelled() }}
        with:
          report_paths: junit/e2e/*.xml
