---
name: e2e

on:
  push:
    paths:
      - 'vm/**'
      - 'uv.lock'
  schedule:
    # First day of every month at 2:00 AM UTC.
    - cron: '0 2 1 * *'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.13'

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ansible
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Restore cache
        uses: actions/cache@v5
        with:
          path: |
            vm/.cache/docker/binpkgs
            vm/.cache/distfiles
            vm/.cache/repos
          key: gentoo-e2e-${{ github.run_id }}
          restore-keys: gentoo-e2e-
      - name: Run e2e scenario
        run: cd vm && uv run --extra vm molecule test --scenario-name e2e
      - name: Save cache
        uses: actions/cache/save@v5
        if: always()
        with:
          path: |
            vm/.cache/docker/binpkgs
            vm/.cache/distfiles
            vm/.cache/repos
          key: gentoo-e2e-${{ github.run_id }}
      - name: Publish e2e test results
        uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          report_paths: vm/junit/e2e/*.xml
