---
name: lint

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.13'

anchors:
  checkout: &checkout
    name: Checkout
    uses: actions/checkout@v6
    with:
      persist-credentials: false

  setup-ansible: &setup-ansible
    uses: ./.github/actions/setup-ansible
    with:
      python-version: ${{ env.PYTHON_VERSION }}

  setup-python: &setup-python
    uses: ./.github/actions/setup-python
    with:
      python-version: ${{ env.PYTHON_VERSION }}

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - <<: *checkout
      - <<: *setup-ansible
      - name: Run ansible-lint
        run: cd vm/ && uv run --extra lint ansible-lint --sarif-file ansible-lint.sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: ${{ !cancelled() }}
        with:
          sarif_file: vm/ansible-lint.sarif
          category: ansible-lint

  ruff-format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - <<: *checkout
      - <<: *setup-python
      - name: Run ruff format
        run: uv run --extra lint ruff format --check --output-format github

  ruff-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - <<: *checkout
      - <<: *setup-python
      - name: Run ruff check
        run: uv run --extra lint ruff check --output-format sarif --output-file ruff.sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: ${{ !cancelled() }}
        with:
          sarif_file: ruff.sarif
          category: ruff

  yamllint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - <<: *checkout
      - <<: *setup-python
      - name: Run yamllint
        run: uv run --extra lint yamllint -f github .

  all-checks:
    if: ${{ !cancelled() }}
    needs: [ansible-lint, ruff-format, ruff-lint, yamllint]
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - if: >-
          ${{ contains(needs.*.result, 'failure')
          || contains(needs.*.result, 'cancelled') }}
        run: exit 1
