---
name: publish

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*'

env:
  PYTHON_VERSION: '3.13'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install uv
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Build
        run: uv build
      - name: Create GitHub release
        run: gh release dist/*
