---
name: publish

on:
  push:
    tags:
      - 'v*'

env:
  PYTHON_VERSION: '3.13'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install uv
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Build
        run: uv build
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
