---
name: python-test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.13'

jobs:
  ty:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run ty
        run: uv run --extra lint ty check --output-format junit > ty.xml elogviewer.py tests/
      - name: Publish ty results
        uses: mikepenz/action-junit-report@v6
        if: ${{ !cancelled() }}
        with:
          report_paths: ty.xml

  pytest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install qt deps
        run: sudo apt update && sudo apt install -y libegl1
      - name: Run pytest
        run: PYTHONPATH=. QT_QPA_PLATFORM=offscreen uv run --extra test pytest --junit-xml=pytest.xml
      - name: Publish pytest results
        uses: mikepenz/action-junit-report@v6
        if: ${{ !cancelled() }}
        with:
          report_paths: pytest.xml

  all-checks:
    if: ${{ !cancelled() }}
    needs: [ty, pytest]
    runs-on: ubuntu-latest
    steps:
      - if: >-
          ${{ contains(needs.*.result, 'failure')
          || contains(needs.*.result, 'cancelled') }}
        run: exit 1
